# DO NOT EDIT THIS FILE!
#
# Python module RGBDCamera__POA generated by omniidl

import omniORB
omniORB.updateModule("RGBDCamera__POA")

# ** 1. Stub files contributing to this module
import DepthCamera_idl

# ** 2. Sub-modules

# ** 3. End
