# DO NOT EDIT THIS FILE!
#
# Python module ogata generated by omniidl

import omniORB
omniORB.updateModule("ogata")

# ** 1. Stub files contributing to this module
import TidyUpManager_idl

# ** 2. Sub-modules

# ** 3. End
